services:
  api:
    container_name: "api"
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - datacat.client.url=http://localhost:3000
      - datacat.auth.secret=changeme
      - datacat.auth.issuer=http://localhost:8080
      - datacat.users.admin.password=s3cret
      - spring.mail.port=2500
      - spring.mail.host=mail
      - spring.neo4j.authentication.username=neo4j
      - spring.neo4j.authentication.password=s3cret
      - spring.neo4j.uri=bolt://db:7687
    depends_on:
      - db
      - mail
    command: [
        "wait-for-it", "db:7687", "--timeout=300", "--",
        "wait-for-it", "mail:2500", "--timeout=30", "--",
        "java", "--enable-preview", "org.springframework.boot.loader.launch.JarLauncher" ]

  db:
    container_name: "db"
    image: neo4j:5.26.4
    ports:
      - "7687:7687"
      - "7474:7474"
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/s3cret
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - "dbdata:/data"
      - "dblogs:/logs"
    healthcheck:
      test: perl -MIO::Socket::INET -e 'exit(! defined( IO::Socket::INET->new("localhost:7687")))'

  mail:
    container_name: "mail"
    image: bentrm/mailslurper:1.14.1
    ports:
      - "2500:2500"
      - "9080:9080"
      - "9085:9085"
    restart: unless-stopped
    volumes:
      - "./mailslurper-config.json:/config.json:ro"
      - "mail:/data"

volumes:
  dbdata:
  dblogs:
  mail:
