version: "3.7"

# Simple compose configuration to provide required services to
# test the api during development.

services:
  api:
    container_name: "api"
    build: .
    ports:
      - "8080:8080"
    environment:
      - MANAGEMENT_ENDPOINT_HEALTH_SHOWDETAILS=ALWAYS
      - SPRING_MAIL_PORT=2500
      - SPRING_MAIL_HOST=mail
      - SPRING_DATA_NEO4J_USERNAME=neo4j
      - SPRING_DATA_NEO4J_PASSWORD=s3cret
      - SPRING_DATA_NEO4J_URI=bolt://db:7687
    depends_on:
      - db
      - mail
    command: [
        "wait-for-it", "db:7687", "--timeout=300", "--",
        "wait-for-it", "mail:2500", "--timeout=30", "--",
        "java", "--enable-preview", "org.springframework.boot.loader.JarLauncher" ]

  db:
    container_name: "db"
    image: neo4j:4.1
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      - NEO4J_AUTH=neo4j/s3cret
      - NEO4JLABS_PLUGINS=["apoc"]
    volumes:
      - "dbdata:/data"
      - "dblogs:/logs"

  mail:
    container_name: "mail"
    image: bentrm/mailslurper:1.14.1
    ports:
      - "2500:2500"
    volumes:
      - "mail:/data"

volumes:
  dbdata:
  dblogs:
  mail:
