spring:
  profiles:
    active: dev

logging:
  level:
    de.bentrm.datacat: DEBUG

spring.data.neo4j:
  uri: "bolt://localhost:7687"
  username: neo4j
  password: secret

datacat:
  users:
    - username: admin
      firstName: Admin
      lastName: Tester
      email: tester+admin@datacat.local
      roles:
        - ADMIN
        - USER
        - READONLY

  auth:
    secret: change-this-in-production
    issuer: datacat.local

  mail:
    confirmLink: http://localhost:3000/confirm?token=
    from: no-reply@datacat.local
