logging:
  level:
    de.bentrm: debug

datacat:
  users:
    admin:
      firstName: Admin
      lastName: Tester
      email: tester+admin@datacat.local
      roles:
        - ADMIN
        - USER
        - READONLY
    user:
      firstName: User
      lastName: Tester
      email: tester+user@datacat.local
      roles:
        - USER
        - READONLY
    guest:
      firstName: Guest
      lastName: Tester
      email: tester+guest@datacat.local
      roles:
        - READONLY
