management:
  endpoints.web.exposure.include: "auditevents,info,health,prometheus"
  endpoint:
    auditevents:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

spring:
  data:
    neo4j:
      uri: "bolt://localhost:7687"
      username: neo4j
      password: secret
      open-in-view: false
      auto-index: update

graphql:
  servlet:
    enabled: true
    corsEnabled: true
    mapping: /graphql
    exception-handlers-enabled: true
    tracingEnabled: false
    actuator-metrics: true

logging:
  level:
    de.bentrm.datacat:
      auth: DEBUG
      graphql: DEBUG
      service: DEBUG

datacat:
  auth:
    secret: my-secret
    issuer: datacat-demo
    admin:
      password: s3cret
      username: admin
