spring:
  data:
    neo4j:
      uri: "bolt://localhost:7687"
      username: neo4j
      password: secret
      open-in-view: false
      auto-index: update

graphql:
  servlet:
    enabled: true
    corsEnabled: true
    mapping: /graphql
    exception-handlers-enabled: true
    tracingEnabled: false
    actuator-metrics: true

graphiql:
  enabled: true
  mapping: /graphiql
  cdn:
    enabled: false

logging:
  level:
    org.neo4j.ogm.drivers.bolt.request.BoltRequest: DEBUG
